#!/usr/bin/env python3
"""Faithful port of kernel/time/timeconst.bc -> timeconst.h for a single HZ.
Bypasses the vendor's GNU-bc -q hang. Output must match bc exactly.
"""
import sys

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def fmul(b, n, d):
    return (2**b * n + d - 1) // d

def fadj(b, n, d):
    d = d // gcd(n, d)
    return (2**b * (d - 1)) // d

def fmuls(b, n, d):
    s = 0
    while True:
        m = fmul(s, n, d)
        if m >= 2**(b - 1):
            return s
        s += 1

def timeconst(hz):
    out = []
    out.append("/* Automatically generated by kernel/time/timeconst.bc */")
    out.append("/* Time conversion constants for HZ == %d */" % hz)
    out.append("")
    out.append("#ifndef KERNEL_TIMECONST_H")
    out.append("#define KERNEL_TIMECONST_H")
    out.append("")
    out.append("#include <linux/param.h>")
    out.append("#include <linux/types.h>")
    out.append("")
    out.append("#if HZ != %d" % hz)
    out.append('#error "include/generated/timeconst.h has the wrong HZ value!"')
    out.append("#endif")
    out.append("")
    if hz < 2:
        out.append("#error Totally bogus HZ value!")
    else:
        s = fmuls(32, 1000, hz)
        out.append("#define HZ_TO_MSEC_MUL32\tU64_C(0x%x)" % fmul(s, 1000, hz))
        out.append("#define HZ_TO_MSEC_ADJ32\tU64_C(0x%x)" % fadj(s, 1000, hz))
        out.append("#define HZ_TO_MSEC_SHR32\t%d" % s)
        s = fmuls(32, hz, 1000)
        out.append("#define MSEC_TO_HZ_MUL32\tU64_C(0x%x)" % fmul(s, hz, 1000))
        out.append("#define MSEC_TO_HZ_ADJ32\tU64_C(0x%x)" % fadj(s, hz, 1000))
        out.append("#define MSEC_TO_HZ_SHR32\t%d" % s)
        cd = gcd(hz, 1000)
        out.append("#define HZ_TO_MSEC_NUM\t\t%d" % (1000 // cd))
        out.append("#define HZ_TO_MSEC_DEN\t\t%d" % (hz // cd))
        out.append("#define MSEC_TO_HZ_NUM\t\t%d" % (hz // cd))
        out.append("#define MSEC_TO_HZ_DEN\t\t%d" % (1000 // cd))
        out.append("")
        s = fmuls(32, 1000000, hz)
        out.append("#define HZ_TO_USEC_MUL32\tU64_C(0x%x)" % fmul(s, 1000000, hz))
        out.append("#define HZ_TO_USEC_ADJ32\tU64_C(0x%x)" % fadj(s, 1000000, hz))
        out.append("#define HZ_TO_USEC_SHR32\t%d" % s)
        s = fmuls(32, hz, 1000000)
        out.append("#define USEC_TO_HZ_MUL32\tU64_C(0x%x)" % fmul(s, hz, 1000000))
        out.append("#define USEC_TO_HZ_ADJ32\tU64_C(0x%x)" % fadj(s, hz, 1000000))
        out.append("#define USEC_TO_HZ_SHR32\t%d" % s)
        cd = gcd(hz, 1000000)
        out.append("#define HZ_TO_USEC_NUM\t\t%d" % (1000000 // cd))
        out.append("#define HZ_TO_USEC_DEN\t\t%d" % (hz // cd))
        out.append("#define USEC_TO_HZ_NUM\t\t%d" % (hz // cd))
        out.append("#define USEC_TO_HZ_DEN\t\t%d" % (1000000 // cd))
        cd = gcd(hz, 1000000000)
        out.append("#define HZ_TO_NSEC_NUM\t\t%d" % (1000000000 // cd))
        out.append("#define HZ_TO_NSEC_DEN\t\t%d" % (hz // cd))
        out.append("#define NSEC_TO_HZ_NUM\t\t%d" % (hz // cd))
        out.append("#define NSEC_TO_HZ_DEN\t\t%d" % (1000000000 // cd))
        out.append("")
        out.append("#endif /* KERNEL_TIMECONST_H */")
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    print(timeconst(int(sys.argv[1]) if len(sys.argv) > 1 else 100), end="")